export const NANSEN_COMMANDS = [
  {
    command: 'research smart-money netflow',
    description: 'Net flow of tokens into/out of smart money wallets. Shows accumulation or distribution.',
    requires: ['--chain'],
    optional: ['--token', '--timeframe', '--limit', '--fields', '--labels'],
    returns: 'token_symbol, token_address, net_flow_usd, inflow_usd, outflow_usd',
  },
  {
    command: 'research smart-money dex-trades',
    description: 'Recent DEX trades by labeled smart money wallets.',
    requires: ['--chain'],
    optional: ['--token', '--timeframe', '--limit', '--labels'],
    returns: 'address, token_symbol, trade_type (buy/sell), value_usd, tx_hash',
  },
  {
    command: 'research smart-money holdings',
    description: 'Current token holdings across smart money wallets.',
    requires: ['--chain'],
    optional: ['--timeframe', '--limit', '--fields'],
    returns: 'token_symbol, token_address, value_usd, pnl_usd',
  },
  {
    command: 'research token screener',
    description: 'Screen tokens by volume, price change, market metrics.',
    requires: ['--chain'],
    optional: ['--timeframe', '--limit', '--sort'],
    returns: 'token_symbol, token_address, price_usd, volume_24h, price_change_pct, market_cap',
  },
  {
    command: 'research token holders',
    description: 'Top holders of a specific token with balances and labels.',
    requires: ['--chain', '--token'],
    optional: ['--limit'],
    returns: 'address, value_usd, balance, label, percentage_held',
  },
  {
    command: 'research token flow-intelligence',
    description: 'Flow signals — detects unusual inflow/outflow patterns for a token.',
    requires: ['--chain', '--token'],
    optional: [],
    returns: 'flow direction, magnitude, entity labels, time',
  },
  {
    command: 'research token who-bought-sold',
    description: 'Breakdown of which entities bought vs sold a token recently.',
    requires: ['--chain', '--token'],
    optional: ['--days'],
    returns: 'address, side (bought/sold), value_usd, label',
  },
  {
    command: 'research token pnl-leaderboard',
    description: 'PnL ranking of top holders — shows who is in profit and who is underwater.',
    requires: ['--chain', '--token'],
    optional: ['--limit'],
    returns: 'address, pnl_usd, realized_pnl_usd, unrealized_pnl_usd, label',
  },
  {
    command: 'research token dex-trades',
    description: 'Recent DEX trades for a specific token.',
    requires: ['--chain', '--token'],
    optional: ['--timeframe', '--limit'],
    returns: 'address, trade_type, value_usd, token_amount, tx_hash',
  },
  {
    command: 'research token transfers',
    description: 'Token transfer events — large transfers can signal dumps or accumulation.',
    requires: ['--chain', '--token'],
    optional: ['--days', '--limit'],
    returns: 'from_address, to_address, value_usd, tx_hash',
  },
  {
    command: 'research token flows',
    description: 'Aggregated token flows between entity types (CEX, DEX, wallets).',
    requires: ['--chain', '--token'],
    optional: ['--days'],
    returns: 'from_entity, to_entity, flow_usd',
  },
  {
    command: 'research token perp-trades',
    description: 'Perpetual futures trades on a token (Hyperliquid).',
    requires: ['--chain', '--token'],
    optional: ['--limit'],
    returns: 'address, side (long/short), size_usd, entry_price',
  },
  {
    command: 'research token perp-positions',
    description: 'Open perpetual positions on a token.',
    requires: ['--chain', '--token'],
    optional: ['--limit'],
    returns: 'address, side, size_usd, entry_price, pnl_usd',
  },
  {
    command: 'research token perp-pnl-leaderboard',
    description: 'Perp PnL leaderboard — who is making/losing money on derivatives.',
    requires: ['--chain', '--token'],
    optional: ['--limit'],
    returns: 'address, pnl_usd, total_trades',
  },
  {
    command: 'research profiler balance',
    description: 'Current token balances for a specific wallet address.',
    requires: ['--chain', '--address'],
    optional: [],
    returns: 'token_symbol, token_address, balance, value_usd',
  },
  {
    command: 'research profiler pnl-summary',
    description: 'Profit/loss summary for a wallet.',
    requires: ['--chain', '--address'],
    optional: [],
    returns: 'total_pnl_usd, realized_pnl_usd, unrealized_pnl_usd, win_rate',
  },
  {
    command: 'research profiler transactions',
    description: 'Recent transactions for a wallet address.',
    requires: ['--chain', '--address'],
    optional: ['--days', '--limit'],
    returns: 'tx_hash, type, value_usd, token_symbol, timestamp',
  },
  {
    command: 'research profiler counterparties',
    description: 'Who a wallet interacts with most — reveals clusters and relationships.',
    requires: ['--chain', '--address'],
    optional: ['--days', '--limit'],
    returns: 'counterparty_address, label, transaction_count, value_usd',
  },
  {
    command: 'research profiler labels',
    description: 'Get Nansen labels for a wallet address (e.g., Fund, Smart Trader, CEX).',
    requires: ['--chain', '--address'],
    optional: [],
    returns: 'address, labels[]',
  },
  {
    command: 'research profiler historical-balances',
    description: 'Historical token balances over time for a wallet.',
    requires: ['--chain', '--address'],
    optional: ['--limit'],
    returns: 'date, token_symbol, balance, value_usd',
  },
  {
    command: 'research search entities',
    description: 'Search for wallets, tokens, or protocols by name or address.',
    requires: ['--query'],
    optional: ['--chain'],
    returns: 'entity_name, address, type, labels',
  },
  {
    command: 'research perp screener',
    description: 'Screen perpetual futures markets.',
    requires: [],
    optional: ['--limit', '--sort'],
    returns: 'symbol, open_interest, volume_24h, funding_rate',
  },
];

export const SUPPORTED_CHAINS = [
  'ethereum', 'solana', 'base', 'bnb', 'arbitrum', 'polygon',
  'optimism', 'avalanche', 'linea', 'scroll', 'mantle', 'ronin',
  'sei', 'sonic', 'hyperevm',
];

export const CLAUDE_MODEL = 'claude-sonnet-4-20250514';
export const MAX_AGENT_STEPS = 4;
export const MAX_COMMANDS_PER_STEP = 5;
